// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Login() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"min-h-screen w-full relative overflow-hidden\"><!-- Playful background blobs --><div class=\"pointer-events-none absolute inset-0 -z-10\"><div class=\"absolute -top-24 -left-16 h-80 w-80 rounded-full bg-pink-300/40 blur-3xl\"></div><div class=\"absolute top-24 -right-16 h-96 w-96 rounded-full bg-purple-300/40 blur-3xl\"></div></div><div class=\"mx-auto max-w-6xl px-6 py-16\"><div class=\"mx-auto max-w-md rounded-3xl bg-white/80 backdrop-blur border border-gray-200 shadow-sm p-8\"><div class=\"flex items-center gap-3 mb-4\"><div class=\"h-10 w-10 rounded-xl bg-gradient-to-br from-pink-600 to-rose-600 grid place-items-center text-white text-xl\">🐍</div><div><h1 class=\"text-2xl font-extrabold tracking-tight\">Entrar</h1><p class=\"text-sm text-gray-600\">Digite o código de 9 letras para vincular seu time.</p></div></div><form hx-post=\"/login\" hx-target=\"body\" hx-swap=\"outerHTML\" class=\"space-y-5\"><label for=\"code\" class=\"block text-sm font-medium text-gray-700\">Código do time</label> <input id=\"code\" name=\"code\" type=\"text\" required placeholder=\"EX: ABCDEFGHI\" class=\"w-full px-4 py-3 bg-white border border-gray-300 focus:border-pink-500 focus:ring-2 focus:ring-pink-200 outline-none rounded-lg transition\"> <button type=\"submit\" class=\"w-full px-4 py-3 bg-pink-600 text-white font-semibold rounded-lg shadow hover:bg-pink-700 transition\">Entrar</button><p class=\"text-xs text-gray-500\">Ao prosseguir, você concorda com os termos da competição.</p></form></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layout("Localsnake • Entrar").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
