// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Code struct {
	ID        int64
	Code      string
	CreatedAt sql.NullTime
}

type Snake struct {
	ID        int64
	Path      string
	Lang      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	TeamID    int64
}

type Team struct {
	ID        int64
	Name      string
	IsAdmin   sql.NullBool
	CodeID    int64
	CreatedAt sql.NullTime
}
