// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

type BoardPoint struct{ X, Y int }
type BoardSnake struct {
	Name  string
	Body  []BoardPoint
	Color string
	Score int
}
type BoardData struct {
	Width, Height int
	Foods         []BoardPoint
	Snakes        []BoardSnake
}

func BoardMockState() BoardData {
	return BoardData{
		Width:  10,
		Height: 10,
		Foods:  []BoardPoint{{3, 3}, {0, 0}, {4, 5}},
		Snakes: []BoardSnake{
			{Name: "abacate", Score: 3, Color: "#ef4444", Body: []BoardPoint{{1, 3}, {2, 3}, {3, 3}}},
			{Name: "jorge", Score: 3, Color: "#22c55e", Body: []BoardPoint{{9, 6}, {9, 7}, {9, 8}}},
		},
	}
}

func BBB(data BoardData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
